# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0007_auto_20170212_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='Node')),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='maps.Map')),
            ],
        ),
    ]
