# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-22 12:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20161217_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='data',
            new_name='map',
        ),
        migrations.AlterField(
            model_name='map',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to=settings.AUTH_USER_MODEL),
        ),
    ]
