# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20161222_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='map',
            new_name='title',
        ),
        migrations.AddField(
            model_name='map',
            name='descript',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='node',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='path',
            field=models.TextField(null=True),
        ),
    ]
