# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 12:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170121_1543'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='descript',
        ),
        migrations.RemoveField(
            model_name='map',
            name='node',
        ),
        migrations.RemoveField(
            model_name='map',
            name='path',
        ),
        migrations.AlterField(
            model_name='map',
            name='title',
            field=models.TextField(default='Untitled'),
        ),
    ]
