# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20170212_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
