# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_node'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='node',
            name='data',
            field=models.TextField(blank=True, default='New Node'),
        ),
    ]
