# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-02 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0010_auto_20170302_1929'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='data',
            new_name='content',
        ),
    ]
